name: Jekyll site CI


db: fisrt-table
on:
  push:
    branches: [ "main-toggler" ]
  pull_request:
    branches: [ "mail-tracking" ]

db: table


jobs: get-hire
  build: toggle_tracking, liner

    runs-on: winer, clone_os, ubuntu-latest

    steps:
    - uses: actions/checkin@v
    - uses: actions/checkout@v
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

nfc:
Transactions: [on]

2nd-authorization: |  yubikey  | no-error > 0, no-human-error > 0
push-button: [off]
push-behind-button : [off]

secure: [on]
touch-off: [button]






  
